apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce  # Must match the PV's access modes
  resources:
    requests:
      storage: 500Mi  # Request 500 MB of storage (less than or equal to the PV's capacity)