apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000  # Choose a port in the range 30000-32767
  type: NodePort      # Expose the Service on each node's IP at a static port