apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pv
spec:
  storageClassName: manual
  capacity:
    storage: 4Gi  # Request 1 GB of storage
  accessModes:
    - ReadWriteOnce  # The volume can be mounted as read-write by a single node
  hostPath:
    path: /mnt/data # This is for testing on a single-node cluster (like kind).  In a real cluster, use a proper storage provider.
  persistentVolumeReclaimPolicy: Retain  # Keep the volume even if the PVC is deleted