apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 4  # Specify 4 replicas
  selector:
    matchLabels:
      app: nginx  # This selector must match the Pod template's labels
  template:
    metadata:
      labels:
        app: nginx  # Labels for the Pods created by this Deployment
    spec:
      containers:
      - name: nginx-container
        image: nginx:latest
        ports:
        - containerPort: 80